const countryCodes = {
  AR: 'Argentina',
  AW: 'Aruba',
  BS: 'Bahamas',
  BB: 'Barbados',
  BZ: 'Belize',
  BM: 'Bermuda',
  BR: 'Brazil',
  CA: 'Canada',
  CL: 'Chile',
  CO: 'Colombia',
  CR: 'Costa Rica',
  DO: 'Dominican Republic',
  EC: 'Ecuador',
  SV: 'El Salvador',
  GT: 'Guatemala',
  HN: 'Honduras',
  JM: 'Jamaica',
  MX: 'Mexico',
  NI: 'Nicaragua',
  PA: 'Panama',
  PY: 'Paraguay',
  PE: 'Peru',
  PR: 'Puerto Rico',
  QA: 'Qatar',
  TT: 'Trinidad and Tobago',
  US: 'United States of America',
  UY: 'Uruguay',
  VE: 'Venezuela (Bolivarian Republic of)'
}

export default countryCodes
